version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1
workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git
parameters:
  app-name:
    default: HEROKU_APP_NAME
  api-key:
    default: $HEROKU_API_KEY

